// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXxQAxkeayViFY0aTvmATP39y_SnBgmzI',
    appId: '1:1057514468980:web:7d2380fa015cc76640c321',
    messagingSenderId: '1057514468980',
    projectId: 'ration-seva',
    authDomain: 'ration-seva.firebaseapp.com',
    storageBucket: 'ration-seva.appspot.com',
    measurementId: 'G-P9H7G42JTL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTfTDcoeEYRM7e7FFxDS-AgzUkREBEPPI',
    appId: '1:1057514468980:android:515c993d0b94b33340c321',
    messagingSenderId: '1057514468980',
    projectId: 'ration-seva',
    storageBucket: 'ration-seva.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVAXN7uIZ-80FWsiApc_WItf2rkBDEAxU',
    appId: '1:1057514468980:ios:dc3ee70b9150dcc440c321',
    messagingSenderId: '1057514468980',
    projectId: 'ration-seva',
    storageBucket: 'ration-seva.appspot.com',
    iosBundleId: 'com.example.rationSeva',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVAXN7uIZ-80FWsiApc_WItf2rkBDEAxU',
    appId: '1:1057514468980:ios:6af69614cb9f21fb40c321',
    messagingSenderId: '1057514468980',
    projectId: 'ration-seva',
    storageBucket: 'ration-seva.appspot.com',
    iosBundleId: 'com.example.rationSeva.RunnerTests',
  );
}
